@TodoApi2_HostAddress = http://localhost:5273

GET {{TodoApi2_HostAddress}}/weatherforecast/
Accept: application/json

POST {{TodoApi2_HostAddress}}/login/
Content-Type: application/json

POST {{TodoApi2_HostAddress}}/users/
Content-Type: application/json

POST {{TodoApi2_HostAddress}}/delete/
Content-Type: application/json

###


